# <span style="color:red"> QTM 151 - Practice Quiz </span>

<font size = "5">

Import pandas

In [1]:
import pandas as pd


<font size = "5">

(1) Replace the values of a column

<font size = "3">

- Consider the DataFrame ``df_movies`` created below.
- In the "country" column, change the values "American" and "Korean" to "USA" and "ROK" respectively
- Do this by using the ``.replace`` method.

In [6]:
# create example DataFrame - don't change this
titles = ["Past Lives", "Citizen Kane", "Revenge", "Okja", "Shutter", 
    "A Tale of Two Sisters", "La Chinoise", "The Umbrellas of Cherbourg", "House",
    "Suspiria", "Blue Velvet"]
country = ["American", "American", "France", "Korean", "Thailand", "Korean", "France",
    "France", "Japan", "Italy", "American"]
runtime = [106, 119, 108, 120, 97, 115, 96, 91, 88, 98, 120]
year = [2023, 1941, 2017, 2017, 2004, 2003, 1967, 1964, 1977, 1977, 1986]
movie_dict = {"title" : titles, "country" : country, "runtime" : runtime, "year" : year}
df_movies = pd.DataFrame(movie_dict)
print(df_movies)


# your answer here

df_movies["country"] = df_movies["country"].replace(["American", "Korean"], 
                            ["USA", "ROK"])
print()
print(df_movies)

                         title   country  runtime  year
0                   Past Lives  American      106  2023
1                 Citizen Kane  American      119  1941
2                      Revenge    France      108  2017
3                         Okja    Korean      120  2017
4                      Shutter  Thailand       97  2004
5        A Tale of Two Sisters    Korean      115  2003
6                  La Chinoise    France       96  1967
7   The Umbrellas of Cherbourg    France       91  1964
8                        House     Japan       88  1977
9                     Suspiria     Italy       98  1977
10                 Blue Velvet  American      120  1986

                         title   country  runtime  year
0                   Past Lives       USA      106  2023
1                 Citizen Kane       USA      119  1941
2                      Revenge    France      108  2017
3                         Okja       ROK      120  2017
4                      Shutter  Thailand       97  2004
5        A Tale of Two Sisters       ROK      115  2003
6                  La Chinoise    France       96  1967
7   The Umbrellas of Cherbourg    France       91  1964
8                        House     Japan       88  1977
9                     Suspiria     Italy       98  1977
10                 Blue Velvet       USA      120  1986

<font size = "5">

(2) Recode a numeric column

<font size = "3">

- Consider the DataFrame ``df_movies`` created above
- Recode the "year" column into a new column "year_brackets" <br>
with the following categories:

$\qquad$ ``` ["1941-1967","1968-1999","2000-onwards"] ```

$\qquad$ HINT: Use the "pd.cut()" command.

In [3]:
# your code here

df_movies["year_brackets"] = pd.cut(x = df_movies["year"], 
                bins=[1940, 1967, 1999, float("inf")], 
                labels = ["1941-1967", "1968-1999", "2000-onwards"])

print(df_movies)

                         title   country  runtime  year year_brackets
0                   Past Lives       USA      106  2023  2000-onwards
1                 Citizen Kane       USA      119  1941     1941-1967
2                      Revenge    France      108  2017  2000-onwards
3                         Okja       ROK      120  2017  2000-onwards
4                      Shutter  Thailand       97  2004  2000-onwards
5        A Tale of Two Sisters       ROK      115  2003  2000-onwards
6                  La Chinoise    France       96  1967     1941-1967
7   The Umbrellas of Cherbourg    France       91  1964     1941-1967
8                        House     Japan       88  1977     1968-1999
9                     Suspiria     Italy       98  1977     1968-1999
10                 Blue Velvet       USA      120  1986     1968-1999

<font size = "5">

(3) Rename column

<font size = "3">

- Consider the DataFrame ``df_movies`` created above
- Rename the column "runtime" to "runtime(minutes)"

In [4]:
# Write your answer here:

df_movies.rename(columns={"runtime" : "runtime(minutes)"}, inplace=True)

print(df_movies)

                         title   country  runtime(minutes)  year year_brackets
0                   Past Lives       USA               106  2023  2000-onwards
1                 Citizen Kane       USA               119  1941     1941-1967
2                      Revenge    France               108  2017  2000-onwards
3                         Okja       ROK               120  2017  2000-onwards
4                      Shutter  Thailand                97  2004  2000-onwards
5        A Tale of Two Sisters       ROK               115  2003  2000-onwards
6                  La Chinoise    France                96  1967     1941-1967
7   The Umbrellas of Cherbourg    France                91  1964     1941-1967
8                        House     Japan                88  1977     1968-1999
9                     Suspiria     Italy                98  1977     1968-1999
10                 Blue Velvet       USA               120  1986     1968-1999

<font size = "5">

(4) Merge dataset

<font size = "3">

- Consider the DataFrames ``df_movies`` (created above) and ``df_scores`` (created below)
- Create a new dataset using  ```pd.merge()``` using <br>
"df_movies" as the primary dataset, and <br>
"df_scores" as the secondary dataset, merging on <br>
the column "title"
- You should **ONLY** merge the "imdb_score" column <br>
from the secondary dataset (not the "director" column)

HINT: Use ```[[...]]``` to extract a subset of columns <br>
from the secondary dataset before merging

In [5]:
# create example DataFrame - don't change this
titles = ["Past Lives", "Citizen Kane", "Revenge", "Okja", "Shutter", 
    "A Tale of Two Sisters", "La Chinoise", "The Umbrellas of Cherbourg", "House",
    "Suspiria", "Blue Velvet"]
scores = [7.8, 8.2, 6.4, 7.3, 7.0, 7.1, 6.9, 7.8, 7.2, 7.3, 7.7]
directors = ["Celine Song", "Orson Welles", "Coralie Fargeat", "Bong Joon Ho", 
    "Banjong Pisanthanakun", "Kim Jee-woon", "Jean-Luc Godard", "Jacques Demy", 
    "Nobuhiko Obayashi", "Dario Argento", "David Lynch"]

movie_dict2 = {"title" : titles, "imdb_score" : scores, "director" : directors}
df_scores = pd.DataFrame(movie_dict2)



# Write your answer here:

df_new = pd.merge(left = df_movies, right = df_scores[["title", "imdb_score"]], 
        on = "title", how = "left")
print(df_new)

                         title   country  runtime(minutes)  year  \
0                   Past Lives       USA               106  2023
1                 Citizen Kane       USA               119  1941
2                      Revenge    France               108  2017
3                         Okja       ROK               120  2017
4                      Shutter  Thailand                97  2004
5        A Tale of Two Sisters       ROK               115  2003
6                  La Chinoise    France                96  1967
7   The Umbrellas of Cherbourg    France                91  1964
8                        House     Japan                88  1977
9                     Suspiria     Italy                98  1977
10                 Blue Velvet       USA               120  1986

   year_brackets  imdb_score
0   2000-onwards         7.8
1      1941-1967         8.2
2   2000-onwards         6.4
3   2000-onwards         7.3
4   2000-onwards         7.0
5   2000-onwards         7.1
6      1941-1967         6.9
7      1941-1967         7.8
8      1968-1999         7.2
9      1968-1999         7.3
10     1968-1999         7.7

<font size = "5">

(5) Aggregate and sort

<font size = "3">

- Using the merged dataset you created above, do the following in a single line by chaining:
    - Group the dataset by "country"
    - Aggregate the following statistics: average runtime, maximum runtime, average IMDB score, minimum IMDB score
    - Score by average IMBD score in **descending order**

Print the resulting DataFrame

In [6]:
# Write your answer here:

(df_new.groupby("country").agg(avg_run = ('runtime(minutes)', 'mean'),
                    max_run = ('runtime(minutes)', 'max'),
                    avg_imdb = ('imdb_score', 'mean'),
                    min_imdb = ('imdb_score', 'min')).
                    sort_values(by = "avg_imdb", ascending = False))

             avg_run  max_run  avg_imdb  min_imdb
country
USA       115.000000      120  7.900000       7.7
Italy      98.000000       98  7.300000       7.3
Japan      88.000000       88  7.200000       7.2
ROK       117.500000      120  7.200000       7.1
France     98.333333      108  7.033333       6.4
Thailand   97.000000       97  7.000000       7.0

<font size = "5">

(6) Query and Aggregate

<font size = "3">

Using the merged dataset you created above, do the following in a single line by chaining:

- Subset the observations for 'country == France' using ```.query()```
- Sort the values by year (oldest first)
- Extract the two oldest movies

Print the resulting DataFrame to the screen

In [7]:
# Write your answer here:

df_new.query("country == 'France'").sort_values(by = "year").iloc[:2,:]

,title,country,runtime(minutes),year,year_brackets,imdb_score
7,The Umbrellas of Cherbourg,France,91,1964,1941-1967,7.8
6,La Chinoise,France,96,1967,1941-1967,6.9

## 1. You will load in a .csv, creating a DataFrame. In one of the columns, there are 3 values that need to be replaced with 3 new values. You will be asked to do this using the .replace method once.

In [12]:
fifa_df = pd.read_csv("data_quiz/fifa23_players.csv")

fifa_df["Full Name"] = fifa_df["Full Name"].replace(["Lionel Messi", "Karim Benzema"], 
                            ["GOAT", "Frenchie"])

## 2. You will need to extract a subset of the data based on a logical condition. You will then group this subset, and aggregate one or more statistics. Then you will extract a subset of this data, based on where one of the aggregated statistics is greater than or equal to some value. Full credit will be given if you can do this in 1 line using chaining.

In [26]:
result = (
    fifa_df[fifa_df["Age"] >= 30]
    .groupby("Nationality")
    .agg(avg_overall=("Overall", "mean"), max_val=("Value(in Euro)", "max"))
    .query("avg_overall >= 73")
)

print(result)

              avg_overall    max_val
Nationality
Burkina Faso    73.000000    1000000
Cameroon        73.500000   34500000
Costa Rica      73.000000   10000000
Egypt           77.000000  115500000
Luxembourg      73.000000    2100000
Mexico          76.500000   25500000
Russia          73.444444    6500000
Spain           73.068376   55500000
Togo            74.333333   14500000

## 3. You will recode a numeric variable into a categorical variable (which takes string values). The category will be based on which interval the numeric variable belongs to.

In [30]:
fifa_df["Skill_Level"] = pd.cut(x = fifa_df["Overall"], 
                bins=[0, 59, 69, 79, 90,  float("inf")], 
                labels = ["Bad", "Not Great", "Okay", "Good" ,"Goated"])

print(fifa_df)

       Unnamed: 0        Known As           Full Name  Overall  Potential  \
0               0        L. Messi                GOAT       91         91
1               1      K. Benzema            Frenchie       91         91
2               2  R. Lewandowski  Robert Lewandowski       91         91
3               3    K. De Bruyne     Kevin De Bruyne       91         91
4               4       K. Mbappé       Kylian Mbappé       91         95
...           ...             ...                 ...      ...        ...
18534       18534      D. Collins      Darren Collins       47         56
18535       18535    Yang Dejiang        Dejiang Yang       47         57
18536       18536       L. Mullan         Liam Mullan       47         67
18537       18537    D. McCallion    Daithí McCallion       47         61
18538       18538        N. Rabha         Nabin Rabha       47         50

       Value(in Euro) Positions Played Best Position          Nationality  \
0            54000000               RW           CAM            Argentina
1            64000000            CF,ST            CF               France
2            84000000               ST            ST               Poland
3           107500000           CM,CAM            CM              Belgium
4           190500000            ST,LW            ST               France
...               ...              ...           ...                  ...
18534          110000            ST,RM           CAM  Republic of Ireland
18535           90000              CDM           CDM             China PR
18536          130000               CM            RM     Northern Ireland
18537          100000               CB            CB  Republic of Ireland
18538           60000               LB            LB                India

                                             Image Link  ...  \
0      https://cdn.sofifa.net/players/158/023/23_60.png  ...
1      https://cdn.sofifa.net/players/165/153/23_60.png  ...
2      https://cdn.sofifa.net/players/188/545/23_60.png  ...
3      https://cdn.sofifa.net/players/192/985/23_60.png  ...
4      https://cdn.sofifa.net/players/231/747/23_60.png  ...
...                                                 ...  ...
18534  https://cdn.sofifa.net/players/243/725/23_60.png  ...
18535  https://cdn.sofifa.net/players/261/933/23_60.png  ...
18536  https://cdn.sofifa.net/players/267/823/23_60.png  ...
18537  https://cdn.sofifa.net/players/267/824/23_60.png  ...
18538  https://cdn.sofifa.net/players/261/424/23_60.png  ...

       Weak Foot Rating  Skill Moves  International Reputation  \
0                     4            4                         5
1                     4            4                         4
2                     4            4                         5
3                     5            4                         4
4                     4            5                         4
...                 ...          ...                       ...
18534                 3            2                         1
18535                 3            2                         1
18536                 3            2                         1
18537                 3            2                         1
18538                 3            2                         1

       National Team Name             National Team Image Link  \
0               Argentina  https://cdn.sofifa.net/flags/ar.png
1                  France  https://cdn.sofifa.net/flags/fr.png
2                  Poland  https://cdn.sofifa.net/flags/pl.png
3                 Belgium  https://cdn.sofifa.net/flags/be.png
4                  France  https://cdn.sofifa.net/flags/fr.png
...                   ...                                  ...
18534                   -                                    -
18535                   -                                    -
18536                   -                                    -
18537                   -                                    -
18538                   -                                    -

      National Team Position  National Team Jersey Number  \
0                         RW                           10
1                         ST                           19
2                         ST                            9
3                         RF                            7
4                         ST                           10
...                      ...                          ...
18534                      -                            -
18535                      -                            -
18536                      -                            -
18537                      -                            -
18538                      -                            -

       Attacking Work Rate Defensive Work Rate Skill_Level
0                      Low                 Low      Goated
1                   Medium              Medium      Goated
2                     High              Medium      Goated
3                     High                High      Goated
4                     High                 Low      Goated
...                    ...                 ...         ...
18534               Medium              Medium         Bad
18535               Medium              Medium         Bad
18536                 High              Medium         Bad
18537               Medium              Medium         Bad
18538               Medium              Medium         Bad

[18539 rows x 34 columns]

## 4. You will be asked to do the following: group a dataset by one of its columns/variables, aggregate one or more statistics for each group, and then sort the data by one of the statistics you aggregated over in descending order. Full credit will be given if you can do this in 1 line using chaining.

In [31]:
result = (
    fifa_df[fifa_df["Age"] >= 30]
    .groupby("Nationality")
    .agg(avg_overall=("Overall", "mean"), max_val=("Value(in Euro)", "max"))
    .sort_values(by="avg_overall", ascending=False)
)

print(result)

               avg_overall    max_val
Nationality
Egypt            77.000000  115500000
Mexico           76.500000   25500000
Togo             74.333333   14500000
Cameroon         73.500000   34500000
Russia           73.444444    6500000
...                    ...        ...
Belarus          63.000000     240000
Faroe Islands    62.000000     350000
China PR         61.671429    1600000
Ethiopia         61.000000      70000
India            57.347826     350000

[129 rows x 2 columns]

## 5. Rename one of the column/variable headings of a DataFrame, leaving the others unchanged.

In [32]:
fifa_df.rename(columns={"Club Name" : "Club_Name"}, inplace=True)

print(fifa_df)

       Unnamed: 0        Known As           Full Name  Overall  Potential  \
0               0        L. Messi                GOAT       91         91
1               1      K. Benzema            Frenchie       91         91
2               2  R. Lewandowski  Robert Lewandowski       91         91
3               3    K. De Bruyne     Kevin De Bruyne       91         91
4               4       K. Mbappé       Kylian Mbappé       91         95
...           ...             ...                 ...      ...        ...
18534       18534      D. Collins      Darren Collins       47         56
18535       18535    Yang Dejiang        Dejiang Yang       47         57
18536       18536       L. Mullan         Liam Mullan       47         67
18537       18537    D. McCallion    Daithí McCallion       47         61
18538       18538        N. Rabha         Nabin Rabha       47         50

       Value(in Euro) Positions Played Best Position          Nationality  \
0            54000000               RW           CAM            Argentina
1            64000000            CF,ST            CF               France
2            84000000               ST            ST               Poland
3           107500000           CM,CAM            CM              Belgium
4           190500000            ST,LW            ST               France
...               ...              ...           ...                  ...
18534          110000            ST,RM           CAM  Republic of Ireland
18535           90000              CDM           CDM             China PR
18536          130000               CM            RM     Northern Ireland
18537          100000               CB            CB  Republic of Ireland
18538           60000               LB            LB                India

                                             Image Link  ...  \
0      https://cdn.sofifa.net/players/158/023/23_60.png  ...
1      https://cdn.sofifa.net/players/165/153/23_60.png  ...
2      https://cdn.sofifa.net/players/188/545/23_60.png  ...
3      https://cdn.sofifa.net/players/192/985/23_60.png  ...
4      https://cdn.sofifa.net/players/231/747/23_60.png  ...
...                                                 ...  ...
18534  https://cdn.sofifa.net/players/243/725/23_60.png  ...
18535  https://cdn.sofifa.net/players/261/933/23_60.png  ...
18536  https://cdn.sofifa.net/players/267/823/23_60.png  ...
18537  https://cdn.sofifa.net/players/267/824/23_60.png  ...
18538  https://cdn.sofifa.net/players/261/424/23_60.png  ...

       Weak Foot Rating  Skill Moves  International Reputation  \
0                     4            4                         5
1                     4            4                         4
2                     4            4                         5
3                     5            4                         4
4                     4            5                         4
...                 ...          ...                       ...
18534                 3            2                         1
18535                 3            2                         1
18536                 3            2                         1
18537                 3            2                         1
18538                 3            2                         1

       National Team Name             National Team Image Link  \
0               Argentina  https://cdn.sofifa.net/flags/ar.png
1                  France  https://cdn.sofifa.net/flags/fr.png
2                  Poland  https://cdn.sofifa.net/flags/pl.png
3                 Belgium  https://cdn.sofifa.net/flags/be.png
4                  France  https://cdn.sofifa.net/flags/fr.png
...                   ...                                  ...
18534                   -                                    -
18535                   -                                    -
18536                   -                                    -
18537                   -                                    -
18538                   -                                    -

      National Team Position  National Team Jersey Number  \
0                         RW                           10
1                         ST                           19
2                         ST                            9
3                         RF                            7
4                         ST                           10
...                      ...                          ...
18534                      -                            -
18535                      -                            -
18536                      -                            -
18537                      -                            -
18538                      -                            -

       Attacking Work Rate Defensive Work Rate Skill_Level
0                      Low                 Low      Goated
1                   Medium              Medium      Goated
2                     High              Medium      Goated
3                     High                High      Goated
4                     High                 Low      Goated
...                    ...                 ...         ...
18534               Medium              Medium         Bad
18535               Medium              Medium         Bad
18536                 High              Medium         Bad
18537               Medium              Medium         Bad
18538               Medium              Medium         Bad

[18539 rows x 34 columns]

##  Merge two DataFrames. After merging, the primary DataFrame will have one new column that is obtained from the secondary DataFrame.